name = "simple-vite-cloudflare-starter"
compatibility_date = "2024-12-30"
assets = { not_found_handling = "single-page-application", binding = "ASSETS" }
main = "./src/api/index.ts"
node_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "simple-db"
database_id = "YOUR DB ID"
migrations_dir = "drizzle"